name: build latex document
on:
  push:
    # Just build the docs for anything that's not master
    branches-ignore:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: generate rules
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rules.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet
        uses: xu-cheng/latex-action@v2
        with:
          root_file: planet_sheet.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet
        uses: xu-cheng/latex-action@v2
        with:
          root_file: planet_sheet.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet in grayscale
        run: |
          sudo apt install ghostscript
          gs -sOutputFile=./planet_sheet_grayscale.pdf -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -dCompatibilityLevel=1.4 -dAutoRotatePages=/None -dNOPAUSE -dBATCH ./planet_sheet.pdf

      - name: upload pdf artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ascii_planets
          path: ./*.pdf
