name: generate release
on:
  push:
    branches:
      - master

jobs:
  build_latex:
    name: build and upload assets
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: generate rules
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rules.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet
        uses: xu-cheng/latex-action@v2
        with:
          root_file: planet_sheet.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet
        uses: xu-cheng/latex-action@v2
        with:
          root_file: planet_sheet.tex
          latexmk_use_xelatex: true

      - name: generate planet sheet in grayscale
        run: |
          sudo apt install ghostscript
          gs -sOutputFile=./planet_sheet_grayscale.pdf -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -dCompatibilityLevel=1.4 -dAutoRotatePages=/None -dNOPAUSE -dBATCH ./planet_sheet.pdf

      - name: upload pdf artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ascii_planets
          path: ./*.pdf

  create_release:
    name: create release with assets
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.AP_GITHUB_TOKEN }}
          WITH_V: true

      - name: adjust permissions
        run: |
          sudo chown -R $USER:$(id -gn $USER) ./

      - uses: actions/download-artifact@v2
        with:
          name: ascii_planets

      - name: display structure of downloaded files
        run: ls -R

      - name: prepare release artifact
        run: |
          zip --junk-paths ./ascii_planets_${{ steps.bump.outputs.tag }}.zip ./*.pdf

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AP_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          release_name: ${{ steps.bump.outputs.tag }}
          draft: true
          prerelease: false
          body_path: ./.github/CHANGELOG.md

      - name: upload planet_sheet asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AP_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./ascii_planets_${{ steps.bump.outputs.tag }}.zip
          asset_name: ascii_planets_${{ steps.bump.outputs.tag }}.zip
          asset_content_type: application/zip
